//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalManagement.Financial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameFee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GameFee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalManagement.Financial.FeeByDay[] FeesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Day {
            get {
                return this.DayField;
            }
            set {
                if ((object.ReferenceEquals(this.DayField, value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PortalManagement.Financial.FeeByDay[] Fees {
            get {
                return this.FeesField;
            }
            set {
                if ((object.ReferenceEquals(this.FeesField, value) != true)) {
                    this.FeesField = value;
                    this.RaisePropertyChanged("Fees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeeByDay", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FeeByDay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int GameIdField;
        
        private long FeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GameId {
            get {
                return this.GameIdField;
            }
            set {
                if ((this.GameIdField.Equals(value) != true)) {
                    this.GameIdField = value;
                    this.RaisePropertyChanged("GameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountMoneyStream", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountMoneyStream : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AccountIdField;
        
        private long MoneyField;
        
        private int CreatedDateIntField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CreatedDateInt {
            get {
                return this.CreatedDateIntField;
            }
            set {
                if ((this.CreatedDateIntField.Equals(value) != true)) {
                    this.CreatedDateIntField = value;
                    this.RaisePropertyChanged("CreatedDateInt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Financial.FinancialSoap")]
    public interface FinancialSoap {
        
        // CODEGEN: Generating message contract since element name GetFeeByRangeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFeeByRange", ReplyAction="*")]
        PortalManagement.Financial.GetFeeByRangeResponse GetFeeByRange(PortalManagement.Financial.GetFeeByRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFeeByRange", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalManagement.Financial.GetFeeByRangeResponse> GetFeeByRangeAsync(PortalManagement.Financial.GetFeeByRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentAccountMoneyStreamValue", ReplyAction="*")]
        long GetRecentAccountMoneyStreamValue(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentAccountMoneyStreamValue", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetRecentAccountMoneyStreamValueAsync(long accountId);
        
        // CODEGEN: Generating message contract since element name accountIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountsMoneyStream", ReplyAction="*")]
        PortalManagement.Financial.GetAccountsMoneyStreamResponse GetAccountsMoneyStream(PortalManagement.Financial.GetAccountsMoneyStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountsMoneyStream", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalManagement.Financial.GetAccountsMoneyStreamResponse> GetAccountsMoneyStreamAsync(PortalManagement.Financial.GetAccountsMoneyStreamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeeByRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeeByRange", Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.Financial.GetFeeByRangeRequestBody Body;
        
        public GetFeeByRangeRequest() {
        }
        
        public GetFeeByRangeRequest(PortalManagement.Financial.GetFeeByRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFeeByRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int end;
        
        public GetFeeByRangeRequestBody() {
        }
        
        public GetFeeByRangeRequestBody(int start, int end) {
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeeByRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeeByRangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.Financial.GetFeeByRangeResponseBody Body;
        
        public GetFeeByRangeResponse() {
        }
        
        public GetFeeByRangeResponse(PortalManagement.Financial.GetFeeByRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFeeByRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalManagement.Financial.GameFee[] GetFeeByRangeResult;
        
        public GetFeeByRangeResponseBody() {
        }
        
        public GetFeeByRangeResponseBody(PortalManagement.Financial.GameFee[] GetFeeByRangeResult) {
            this.GetFeeByRangeResult = GetFeeByRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsMoneyStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsMoneyStream", Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.Financial.GetAccountsMoneyStreamRequestBody Body;
        
        public GetAccountsMoneyStreamRequest() {
        }
        
        public GetAccountsMoneyStreamRequest(PortalManagement.Financial.GetAccountsMoneyStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountsMoneyStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountIds;
        
        public GetAccountsMoneyStreamRequestBody() {
        }
        
        public GetAccountsMoneyStreamRequestBody(string accountIds) {
            this.accountIds = accountIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsMoneyStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsMoneyStreamResponse", Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.Financial.GetAccountsMoneyStreamResponseBody Body;
        
        public GetAccountsMoneyStreamResponse() {
        }
        
        public GetAccountsMoneyStreamResponse(PortalManagement.Financial.GetAccountsMoneyStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountsMoneyStreamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalManagement.Financial.AccountMoneyStream[] GetAccountsMoneyStreamResult;
        
        public GetAccountsMoneyStreamResponseBody() {
        }
        
        public GetAccountsMoneyStreamResponseBody(PortalManagement.Financial.AccountMoneyStream[] GetAccountsMoneyStreamResult) {
            this.GetAccountsMoneyStreamResult = GetAccountsMoneyStreamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinancialSoapChannel : PortalManagement.Financial.FinancialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialSoapClient : System.ServiceModel.ClientBase<PortalManagement.Financial.FinancialSoap>, PortalManagement.Financial.FinancialSoap {
        
        public FinancialSoapClient() {
        }
        
        public FinancialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalManagement.Financial.GetFeeByRangeResponse PortalManagement.Financial.FinancialSoap.GetFeeByRange(PortalManagement.Financial.GetFeeByRangeRequest request) {
            return base.Channel.GetFeeByRange(request);
        }
        
        public PortalManagement.Financial.GameFee[] GetFeeByRange(int start, int end) {
            PortalManagement.Financial.GetFeeByRangeRequest inValue = new PortalManagement.Financial.GetFeeByRangeRequest();
            inValue.Body = new PortalManagement.Financial.GetFeeByRangeRequestBody();
            inValue.Body.start = start;
            inValue.Body.end = end;
            PortalManagement.Financial.GetFeeByRangeResponse retVal = ((PortalManagement.Financial.FinancialSoap)(this)).GetFeeByRange(inValue);
            return retVal.Body.GetFeeByRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalManagement.Financial.GetFeeByRangeResponse> PortalManagement.Financial.FinancialSoap.GetFeeByRangeAsync(PortalManagement.Financial.GetFeeByRangeRequest request) {
            return base.Channel.GetFeeByRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalManagement.Financial.GetFeeByRangeResponse> GetFeeByRangeAsync(int start, int end) {
            PortalManagement.Financial.GetFeeByRangeRequest inValue = new PortalManagement.Financial.GetFeeByRangeRequest();
            inValue.Body = new PortalManagement.Financial.GetFeeByRangeRequestBody();
            inValue.Body.start = start;
            inValue.Body.end = end;
            return ((PortalManagement.Financial.FinancialSoap)(this)).GetFeeByRangeAsync(inValue);
        }
        
        public long GetRecentAccountMoneyStreamValue(long accountId) {
            return base.Channel.GetRecentAccountMoneyStreamValue(accountId);
        }
        
        public System.Threading.Tasks.Task<long> GetRecentAccountMoneyStreamValueAsync(long accountId) {
            return base.Channel.GetRecentAccountMoneyStreamValueAsync(accountId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalManagement.Financial.GetAccountsMoneyStreamResponse PortalManagement.Financial.FinancialSoap.GetAccountsMoneyStream(PortalManagement.Financial.GetAccountsMoneyStreamRequest request) {
            return base.Channel.GetAccountsMoneyStream(request);
        }
        
        public PortalManagement.Financial.AccountMoneyStream[] GetAccountsMoneyStream(string accountIds) {
            PortalManagement.Financial.GetAccountsMoneyStreamRequest inValue = new PortalManagement.Financial.GetAccountsMoneyStreamRequest();
            inValue.Body = new PortalManagement.Financial.GetAccountsMoneyStreamRequestBody();
            inValue.Body.accountIds = accountIds;
            PortalManagement.Financial.GetAccountsMoneyStreamResponse retVal = ((PortalManagement.Financial.FinancialSoap)(this)).GetAccountsMoneyStream(inValue);
            return retVal.Body.GetAccountsMoneyStreamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalManagement.Financial.GetAccountsMoneyStreamResponse> PortalManagement.Financial.FinancialSoap.GetAccountsMoneyStreamAsync(PortalManagement.Financial.GetAccountsMoneyStreamRequest request) {
            return base.Channel.GetAccountsMoneyStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalManagement.Financial.GetAccountsMoneyStreamResponse> GetAccountsMoneyStreamAsync(string accountIds) {
            PortalManagement.Financial.GetAccountsMoneyStreamRequest inValue = new PortalManagement.Financial.GetAccountsMoneyStreamRequest();
            inValue.Body = new PortalManagement.Financial.GetAccountsMoneyStreamRequestBody();
            inValue.Body.accountIds = accountIds;
            return ((PortalManagement.Financial.FinancialSoap)(this)).GetAccountsMoneyStreamAsync(inValue);
        }
    }
}
