//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalManagement.muathe24h {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="muathe24h.MechantServicesSoap")]
    public interface MechantServicesSoap {
        
        // CODEGEN: Generating message contract since message TopupMobileRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TopupMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PortalManagement.muathe24h.TopupMobileResponse TopupMobile(PortalManagement.muathe24h.TopupMobileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TopupMobile", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalManagement.muathe24h.TopupMobileResponse> TopupMobileAsync(PortalManagement.muathe24h.TopupMobileRequest request);
        
        // CODEGEN: Generating message contract since message BuyCardsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyCards", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PortalManagement.muathe24h.BuyCardsResponse BuyCards(PortalManagement.muathe24h.BuyCardsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyCards", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalManagement.muathe24h.BuyCardsResponse> BuyCardsAsync(PortalManagement.muathe24h.BuyCardsRequest request);
        
        // CODEGEN: Generating message contract since message ChotCaCHRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChotCaCH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PortalManagement.muathe24h.ChotCaCHResponse ChotCaCH(PortalManagement.muathe24h.ChotCaCHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChotCaCH", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalManagement.muathe24h.ChotCaCHResponse> ChotCaCHAsync(PortalManagement.muathe24h.ChotCaCHRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChotCaCHEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        private string noteField;
        
        private System.DateTime createDateField;
        
        private int amountField;
        
        private int priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APIResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int repCodeField;
        
        private string messageField;
        
        private object dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RepCode {
            get {
                return this.repCodeField;
            }
            set {
                this.repCodeField = value;
                this.RaisePropertyChanged("RepCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopupMobile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopupMobileRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PortalManagement.muathe24h.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string telco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mobileNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool isPrePay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string trace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int type;
        
        public TopupMobileRequest() {
        }
        
        public TopupMobileRequest(PortalManagement.muathe24h.UserCredentials UserCredentials, string telco, string mobileNo, int amount, bool isPrePay, string trace, int type) {
            this.UserCredentials = UserCredentials;
            this.telco = telco;
            this.mobileNo = mobileNo;
            this.amount = amount;
            this.isPrePay = isPrePay;
            this.trace = trace;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopupMobileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TopupMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.muathe24h.APIResult TopupMobileResult;
        
        public TopupMobileResponse() {
        }
        
        public TopupMobileResponse(PortalManagement.muathe24h.APIResult TopupMobileResult) {
            this.TopupMobileResult = TopupMobileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuyCards", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuyCardsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PortalManagement.muathe24h.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string trace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string telco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int quantity;
        
        public BuyCardsRequest() {
        }
        
        public BuyCardsRequest(PortalManagement.muathe24h.UserCredentials UserCredentials, string trace, string telco, int amount, int quantity) {
            this.UserCredentials = UserCredentials;
            this.trace = trace;
            this.telco = telco;
            this.amount = amount;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuyCardsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuyCardsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.muathe24h.APIResult BuyCardsResult;
        
        public BuyCardsResponse() {
        }
        
        public BuyCardsResponse(PortalManagement.muathe24h.APIResult BuyCardsResult) {
            this.BuyCardsResult = BuyCardsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChotCaCH", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChotCaCHRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PortalManagement.muathe24h.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string note;
        
        public ChotCaCHRequest() {
        }
        
        public ChotCaCHRequest(PortalManagement.muathe24h.UserCredentials UserCredentials, string name, string note) {
            this.UserCredentials = UserCredentials;
            this.name = name;
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChotCaCHResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChotCaCHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PortalManagement.muathe24h.ChotCaCHEntity ChotCaCHResult;
        
        public ChotCaCHResponse() {
        }
        
        public ChotCaCHResponse(PortalManagement.muathe24h.ChotCaCHEntity ChotCaCHResult) {
            this.ChotCaCHResult = ChotCaCHResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MechantServicesSoapChannel : PortalManagement.muathe24h.MechantServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MechantServicesSoapClient : System.ServiceModel.ClientBase<PortalManagement.muathe24h.MechantServicesSoap>, PortalManagement.muathe24h.MechantServicesSoap {
        
        public MechantServicesSoapClient() {
        }
        
        public MechantServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MechantServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MechantServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MechantServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalManagement.muathe24h.TopupMobileResponse PortalManagement.muathe24h.MechantServicesSoap.TopupMobile(PortalManagement.muathe24h.TopupMobileRequest request) {
            return base.Channel.TopupMobile(request);
        }
        
        public PortalManagement.muathe24h.APIResult TopupMobile(PortalManagement.muathe24h.UserCredentials UserCredentials, string telco, string mobileNo, int amount, bool isPrePay, string trace, int type) {
            PortalManagement.muathe24h.TopupMobileRequest inValue = new PortalManagement.muathe24h.TopupMobileRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.telco = telco;
            inValue.mobileNo = mobileNo;
            inValue.amount = amount;
            inValue.isPrePay = isPrePay;
            inValue.trace = trace;
            inValue.type = type;
            PortalManagement.muathe24h.TopupMobileResponse retVal = ((PortalManagement.muathe24h.MechantServicesSoap)(this)).TopupMobile(inValue);
            return retVal.TopupMobileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalManagement.muathe24h.TopupMobileResponse> PortalManagement.muathe24h.MechantServicesSoap.TopupMobileAsync(PortalManagement.muathe24h.TopupMobileRequest request) {
            return base.Channel.TopupMobileAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalManagement.muathe24h.TopupMobileResponse> TopupMobileAsync(PortalManagement.muathe24h.UserCredentials UserCredentials, string telco, string mobileNo, int amount, bool isPrePay, string trace, int type) {
            PortalManagement.muathe24h.TopupMobileRequest inValue = new PortalManagement.muathe24h.TopupMobileRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.telco = telco;
            inValue.mobileNo = mobileNo;
            inValue.amount = amount;
            inValue.isPrePay = isPrePay;
            inValue.trace = trace;
            inValue.type = type;
            return ((PortalManagement.muathe24h.MechantServicesSoap)(this)).TopupMobileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalManagement.muathe24h.BuyCardsResponse PortalManagement.muathe24h.MechantServicesSoap.BuyCards(PortalManagement.muathe24h.BuyCardsRequest request) {
            return base.Channel.BuyCards(request);
        }
        
        public PortalManagement.muathe24h.APIResult BuyCards(PortalManagement.muathe24h.UserCredentials UserCredentials, string trace, string telco, int amount, int quantity) {
            PortalManagement.muathe24h.BuyCardsRequest inValue = new PortalManagement.muathe24h.BuyCardsRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.trace = trace;
            inValue.telco = telco;
            inValue.amount = amount;
            inValue.quantity = quantity;
            PortalManagement.muathe24h.BuyCardsResponse retVal = ((PortalManagement.muathe24h.MechantServicesSoap)(this)).BuyCards(inValue);
            return retVal.BuyCardsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalManagement.muathe24h.BuyCardsResponse> PortalManagement.muathe24h.MechantServicesSoap.BuyCardsAsync(PortalManagement.muathe24h.BuyCardsRequest request) {
            return base.Channel.BuyCardsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalManagement.muathe24h.BuyCardsResponse> BuyCardsAsync(PortalManagement.muathe24h.UserCredentials UserCredentials, string trace, string telco, int amount, int quantity) {
            PortalManagement.muathe24h.BuyCardsRequest inValue = new PortalManagement.muathe24h.BuyCardsRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.trace = trace;
            inValue.telco = telco;
            inValue.amount = amount;
            inValue.quantity = quantity;
            return ((PortalManagement.muathe24h.MechantServicesSoap)(this)).BuyCardsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalManagement.muathe24h.ChotCaCHResponse PortalManagement.muathe24h.MechantServicesSoap.ChotCaCH(PortalManagement.muathe24h.ChotCaCHRequest request) {
            return base.Channel.ChotCaCH(request);
        }
        
        public PortalManagement.muathe24h.ChotCaCHEntity ChotCaCH(PortalManagement.muathe24h.UserCredentials UserCredentials, string name, string note) {
            PortalManagement.muathe24h.ChotCaCHRequest inValue = new PortalManagement.muathe24h.ChotCaCHRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.name = name;
            inValue.note = note;
            PortalManagement.muathe24h.ChotCaCHResponse retVal = ((PortalManagement.muathe24h.MechantServicesSoap)(this)).ChotCaCH(inValue);
            return retVal.ChotCaCHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalManagement.muathe24h.ChotCaCHResponse> PortalManagement.muathe24h.MechantServicesSoap.ChotCaCHAsync(PortalManagement.muathe24h.ChotCaCHRequest request) {
            return base.Channel.ChotCaCHAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalManagement.muathe24h.ChotCaCHResponse> ChotCaCHAsync(PortalManagement.muathe24h.UserCredentials UserCredentials, string name, string note) {
            PortalManagement.muathe24h.ChotCaCHRequest inValue = new PortalManagement.muathe24h.ChotCaCHRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.name = name;
            inValue.note = note;
            return ((PortalManagement.muathe24h.MechantServicesSoap)(this)).ChotCaCHAsync(inValue);
        }
    }
}
